### ISSUE TITLE
Update graph on config prop changes

### ISSUE THREAD

**Issue by otisg** [benjeffery/react-plotlyjs#7]
To address this from the README: "Changes to the 'config' prop will not update the graph currently."

**Comment by EJBroeders** [comment]
This bug is because of the if-statement on line 43. The fix is fairly straightforward, just delete the if-statement and create a new plot unconditionally.

Is there something against removing the if-statement? I Think that the componentDidUpdate-method only triggers if there is reason to create a new plot.

**Comment by EJBroeders** [comment]
*poke*

Is this project still maintained?

**Comment by benjeffery** [comment]
Yes! Sorry for not getting to this. Just on mobile now but will attempt to get to this today.

**Comment by benjeffery** [comment]
This was a hangover from when update tried to use `redraw` instead of `newPlot`. Should be fixed in 0.4.1, I kept the if, but added config to it and the `newPlot`

**Comment by benjeffery** [comment]
Reopen if you're not happy!
